define :chord_player do |root| #repeats|
  1.times do
    play chord(root, :minor), release: 0.3
  end
end
in_thread do
  loop do
    sample :drum_snare_hard
    sleep 0.3
    sample :drum_bass_hard
    sleep 0.3
  end
end
sleep 1.8
use_synth :dull_bell
3.times do
  chord_player :Cs
  sleep 0.3
  chord_player :Ds
  sleep 0.3
  chord_player :Fs
  sleep 0.3
  chord_player :Gs
  sleep 0.3
  chord_player :As
  sleep 0.3
  chord_player :As
  sleep 0.3
  chord_player :Gs
  sleep 0.15
  chord_player :Fs
  sleep 0.15
  chord_player :Ds
  sleep 0.3
  chord_player :Cs
  sleep 0.3
  chord_player :Ds
  sleep 0.3
  chord_player :Fs
  sleep 0.3
  chord_player :Gs
  sleep 0.3
  chord_player :As
  sleep 0.6
  chord_player :As
  sleep 0.6
  chord_player :Cs
  sleep 0.3
  chord_player :Ds
  sleep 0.3
  chord_player :Fs
  sleep 0.3
  chord_player :Gs
  sleep 0.3
  chord_player :As
  sleep 0.3
  chord_player :As
  sleep 0.3
  chord_player :Gs
  sleep 0.15
  chord_player :Fs
  sleep 0.15
  chord_player :Ds
  sleep 0.3
  chord_player :Fs
  sleep 0.3
  chord_player :Gs
  sleep 0.15
  chord_player :As
  sleep 0.15
  chord_player :Gs
  sleep 0.15
  chord_player :Fs
  sleep 0.15
  chord_player :Ds
  sleep 0.3
  chord_player :Fs
  sleep 0.6
  chord_player :Fs
  sleep 0.9
end